# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCx1V12tFwoHYUKdeCgPlcsi_4Lt_4im
"""

import pandas as pd
import matplotlib.pyplot as plt

data = {
    "Study_Hours" : [1,2,3,4,5,6,7,8],
    "Score" : [40,50,55,60,65,70,80,90]
}

df = pd.DataFrame(data)

print(df)

print("Average score:", df["Score"].mean())

plt.scatter(df["Study_Hours"], df["Score"])

plt.xlable("Study Hours")
plt.ylable("Exam Score")
plt.title("Study Hours vs Exam Score")

plt.show()